export const sliderItems = [
  // {
  //   id: 1,
  //   img: "https://free.vector6.com/wp-content/uploads/2021/03/freepng1454-hinh-ve-nhan-vat-co-gai-xinh-dep-quyen-ru-png-44.png",
  //   title: "SUMMER SALE",
  //   desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
  //   bg: "fff8f8",
  // },
  // {
  //   id: 2,
  //   img: "https://free.vector6.com/wp-content/uploads/2021/03/freepng1467-hinh-ve-nhan-vat-co-gai-xinh-dep-quyen-ru-png-57.png",
  //   title: "AUTUMN COLLECTION",
  //   desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
  //   bg: "fcf1ed",
  // },
  // {
  //   id: 3,
  //   img: "https://free.vector6.com/wp-content/uploads/2021/03/freepng1466-hinh-ve-nhan-vat-co-gai-xinh-dep-quyen-ru-png-56.png",
  //   title: "LOUNGEWEAR LOVE",
  //   desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
  //   bg: "fbf0f4",
  // },
  {
    _id: "631727e9d2f2ac7b27aabc5b",
    name: "Airpods Wireless Bluetooth Headphones",
    img: "https://manager.remaxvietnam.vn/asset/images/SanPham/phukiendienthoai/tainghe/TWS-V57/av-tws-v57-10062022.png",
    desc: "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    bg: "fff8f8",
  },
  {
    _id: "631727e9d2f2ac7b27aabc5c",
    name: "iPhone 11 Pro 256GB Memory",
    img: "https://hoanghamobile.com/Uploads/2021/03/19/iphone-11-pro-max.png",
    desc: "Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life",
    brand: "Apple",
    category: "Electronics",
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
    bg: "fcf1ed",
  },
  {
    _id: "631727e9d2f2ac7b27aabc5d",
    name: "Cannon EOS 80D DSLR Camera",
    img: "https://camerabox.vn/uploads/shops/camera/canon-camera/2016/canon-eos-80d/canon-eos-80d-1.png",
    desc: "Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design",
    brand: "Cannon",
    category: "Electronics",
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
    bg: "fbf0f4",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "SHIRT STYLE!",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "LOUNGEWEAR LOVE",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    title: "LIGHT JACKETS",
  },
];

export const products = [
  {
    _id: "1",
    name: "Airpods Wireless Bluetooth Headphones",
    img: "https://manager.remaxvietnam.vn/asset/images/SanPham/phukiendienthoai/tainghe/TWS-V57/av-tws-v57-10062022.png",
    description:
      "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "iPhone 11 Pro 256GB Memory",
    img: "https://didongviet.vn/pub/media/catalog/product//i/p/iphone-11-pro-max-vang-didongviet_8.jpg",
    description:
      "Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life",
    brand: "Apple",
    category: "Electronics",
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Cannon EOS 80D DSLR Camera",
    img: "https://camerabox.vn/uploads/shops/camera/canon-camera/2016/canon-eos-80d/canon-eos-80d-1.png",
    description:
      "Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design",
    brand: "Cannon",
    category: "Electronics",
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Sony Playstation 5 White Version",
    img: "https://product.hstatic.net/1000190106/product/ps5_digi_2440e866c0b5432d826e780b33eda318.png",
    description:
      "The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music",
    brand: "Sony",
    category: "Electronics",
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Logitech G-Series Gaming Mouse",
    img: "https://ae01.alicdn.com/kf/Hd665547bca7c4158a7a547148980f4b7F/Logitech-G-Series-Chu-t-Ch-i-Game-G302-G402-G502-Anh-H-ng-Daedalus-Prime.jpg",
    description:
      "Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience",
    brand: "Logitech",
    category: "Electronics",
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "Amazon Echo Dot 3rd Generation",
    img: "https://www.powerplanetonline.com/cdnassets/amazon_echo_dot_3_gen_negro_antracita_altavoz_inteligente_alexa_01_l.jpg",
    description:
      "Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space",
    brand: "Amazon",
    category: "Electronics",
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];
